[theme]
# Primary accent color for interactive elements.
primaryColor = "#87CEEB"

# Background color for the main content area.
backgroundColor = "#333333"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#464646"

# Color used for almost all text.
textColor = "#FFFFFF"
